### ISSUE TITLE
default TREEHUGGER_APP and TREEHUGGER_STAGE to filename

### ISSUE THREAD

**Issue by graingert** [timeoutdigital/treehugger#45]

**Comment by adamchainz** [comment]
Do you mean, have a convention for the filename, or just to set both to the full filename?

**Comment by graingert** [comment]
To be honest I'm not sure what advantage these keys give?

**Comment by adamchainz** [comment]
Mostly to lock down with encryption context, so encrypted data can't be copied between stages/apps.

**Comment by adamchainz** [comment]
Meh I think declaring them is best. The filename isn't always a thing, especially in the recommended way of running on EC2 with user data.
